pipeline {
    agent any
    environment {
        CHROME_DRIVER_URL = 'https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip'
        CHROME_DRIVER_DIR = '/tmp'
    }
    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/amirzh004/SRE_final'
            }
        }
        stage('Install Dependencies') {
            steps {
                sh './mvnw clean install'
            }
        }
        stage('Install unzip and ChromeDriver') {
            steps {
                sh '''
                sudo apt-get update -y
                sudo apt-get install -y unzip
                wget $CHROME_DRIVER_URL -P $CHROME_DRIVER_DIR
                unzip $CHROME_DRIVER_DIR/chromedriver_linux64.zip -d $CHROME_DRIVER_DIR
                chmod +x $CHROME_DRIVER_DIR/chromedriver
                '''
            }
        }
        stage('Unit Tests') {
            steps {
                sh './mvnw test'
            }
        }
        stage('Build') {
            steps {
                sh './mvnw package'
            }
        }
        stage('Deploy to Staging') {
            steps {
                sh 'docker-compose -f docker-compose.staging.yml up -d'
            }
        }
        stage('Acceptance Tests') {
            environment {
                PATH = "/tmp:$PATH"
            }
            steps {
                sh './mvnw verify -Dtest=com.community.LoginPageAcceptanceTest'
            }
        }
        stage('Deploy to Production') {
            steps {
                input message: 'Deploy to production?', ok: 'Deploy'
                sh 'docker-compose -f docker-compose.production.yml up -d'
            }
        }
        stage('Monitoring') {
            steps {
                sh 'curl -X POST http://localhost:9090/-/reload'  // Reload Prometheus configuration
                sh 'curl -X POST http://localhost:9093/-/reload'  // Reload Alertmanager configuration
            }
        }
    }
    post {
        always {
            echo 'Pipeline completed'
        }
        success {
            echo 'Pipeline succeeded'
        }
        failure {
            echo 'Pipeline failed'
        }
    }
}